phrase:
  access_token: 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
  project_id: 872e72d4904023acee437bc424c08241
  push:
    sources:
    - file: ./Furniture Store_en-US.json
      params:
        locale_id: en-US
        file_format: simple_json
  pull:
    targets:
    - file: ./Furniture Store_<locale_name>.json
      params:
        file_format: simple_json
